<div class="container-fluid">
    <div class="row">
        <?php if(count($aList) > 0){ ?>
            <?php foreach($aList as $aImage){ ?>
                <a href="<?php echo Util_Uri::getDFSViewURL($aImage['sKey'].'.'.$aImage['sExt']);?>" target="_blank"><img style="float:left;margin:5px;" src="<?php echo Util_Uri::getDFSViewURL($aImage['sKey'].'.'.$aImage['sExt'], 310, 215, 'c');?>" class="img-responsive" alt="Responsive image"></a>
            <?php } ?>
        <?php } ?>
    </div>
    <?php echo $aPager ?>

</div>
