<!--
placeholder
这个标签显示表单备注
-->

<h3 style="text-align: center">添加产品类别</h3>
<div class="pbody clearfix">
    <form id="myform" class="form-horizontal" role="form" method="post">
        <input type="hidden" class="form-control" name="iMenuID" value="<?php echo isset($aMenu['iMenuID'])?$aMenu['iMenuID']:''?>">
        <div class="form-group has-feedback">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 种类名称：</label>
            <div class="col-sm-3 has-success">
                <input type="text" class="form-control input-validate" validate="!length:2-20" name="sMenuName" value="<?php echo isset($aMenu['sMenuName'])?$aMenu['sMenuName']:''?>">
                <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
            </div>
            <div class="col-sm-3 validate_checktip">

            </div>
        </div>
<!--
        <div class="form-group has-feedback">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 种类名称：</label>
            <div class="col-sm-3 has-error">
                <input type="text" class="form-control input-validate" validate="!length:2-20" name="sMenuName" value="<?php echo isset($aMenu['sMenuName'])?$aMenu['sMenuName']:''?>">
                <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
                <span class="validate_checktip"></span>
            </div>
        </div>
-->
        <div class="form-group">
            <label class="col-sm-2 control-label"><strong style="color:red;">*</strong> 父级种类：</label>
            <div class="col-sm-10">
                <select name="iParentID" class="form-control input-validate col-sm-10">
                    <option value="0">顶级种类</option>
                    <?php
                    if(!empty($aTree)){
                        $iMenuID = isset($aMenu['iParentID'])?$aMenu['iParentID']:'';
                        foreach ($aTree as $v){
                            ?>
                            <option value="<?php echo $v['iMenuID']?>" <?php echo $v['iMenuID']==$iMenuID?'selected':'';?>><?php echo ($v['iLevel']>0?'└'.str_repeat('─', $v['iLevel'] * 2):'') . $v['sMenuName']?></option>
                        <?php }}?>
                </select>
            </div>
        </div>
        <div class="btn-toolbar text-center">
            <input type="submit" class="btn btn-primary" value="保存">
            <button id="cancel"class="btn" onclick="location.href='<?php echo $sListUrl ?>';return false;">取消</button>
        </div>
    </form>
</div>
<script type="text/javascript">
    $(function() {
        $("#myform").validate({submitHandler: function(form) {
            $.post(form.action, $(form).serialize(), function(ret){
                alert(ret.data);
                if (ret.status) {
                    location.href = '/menu/list/';
                }
            }, 'json');
            return false;
        }});

    });
</script>