<div class="p-content">
    <h3 style="text-align: center">产品类别列表</h3>
    <div class="btn-group col-sm-3">
        <button type="button" class="btn btn-block btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            产品分类列表<span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu3">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>
    <button class="btn btn-primary" id="menu_add">
        <i class="icon-plus"></i> 增加菜单
    </button>
</div>
